### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by tp** [waderyan/vscode-atom-keybindings#1]
Been looking for a package like this and would very much try it out, but the docs are missing installation instructions.

Could you be so kind to provide any? Thanks!

**Comment by waderyan** [comment]
Hey Tim, I'll add it to the README soon, but until then check out the instructions [here](http://code.visualstudio.com/docs/editor/extension-gallery)

**Comment by tp** [comment]
@waderyan Sure, I know how to install an extension in general, but this one does not seem bundled/available in the Marketplace.

Don't see a way to install directly from  a Git repository either.

**Comment by tp** [comment]
Found it: menu `Preferences > Keyboard Shortcuts` (also accessible via the command palette) and then copy the keyboard bindings from package.json over)

**Comment by waderyan** [comment]
Yes that can work... I'm trying to remember why I took this off the MP. I believe I simply decided it wasn't complete enough. Please contribute as you see things missing and we can get it back up there.

**Comment by jefffriesen** [comment]
@waderyan any updates on getting this into the marketplace?

**Comment by waderyan** [comment]
hey @jefffriesen there's more work to do. Its not quite ready to be public in the MP. If you want to use it you can copy the keybindings from package.json into your keybindings files. 

Or if you want you can make some contributions that make it a more complete extension.

**Comment by jefffriesen** [comment]
Cool, thanks
