### ISSUE TITLE
Bind ctrl+shift+\ to reveal active file in explorer

### ISSUE THREAD

**Issue by Tyriar** [waderyan/vscode-atom-keybindings#10]
Testing https://github.com/Microsoft/vscode/issues/14318

Linux/Windows: <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>\\</kbd> -> `workbench.files.action.showActiveFileInExplorer`
Mac: <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>\\</kbd> -> `workbench.files.action.showActiveFileInExplorer`

**Comment by waderyan** [comment]
Cool. Added.
