### ISSUE TITLE
alt+shift+up/down doesn't see to use correct command

### ISSUE THREAD

**Issue by Tyriar** [waderyan/vscode-atom-keybindings#12]
Testing https://github.com/Microsoft/vscode/issues/14318

Not sure what's going on here because the command [seems to be set](https://github.com/waderyan/vscode-atom-keybindings/blob/415d38ce21a1ff41a391ff3afee068d6f3ef9186/keybindings/vscode-linux-keybindings.json#L139), but I need to add this to my keybindings.json the cursors to work like in Atom:

``` json
{ "key": "shift+alt+up",          "command": "editor.action.insertCursorAbove",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+down",        "command": "editor.action.insertCursorBelow",
                                     "when": "editorTextFocus" },
```

I do notice the following up the top of my Default keybindings, is it not being overridden correctly? Are the keybindings meant to be overridden when they're lower in the file?

``` json
{ "key": "shift+alt+up",          "command": "cursorColumnSelectUp",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+down",        "command": "cursorColumnSelectDown",
                                     "when": "editorTextFocus" },
```

**Comment by waderyan** [comment]
Strange. According to the [docs](https://code.visualstudio.com/docs/customization/keybindings#_keyboard-rules)...

> When a key is pressed:
> * the rules are evaluated from bottom to top.
> * the first rule that matches, both the key and in terms of when, is accepted.
> * no more rules are processed.
> * if a rule is found and has a command set, the command is executed.

**Comment by waderyan** [comment]
OK I think I know what's going on. The files in `keybindings` folder (which you referenced in your link) are references. I will remove those to avoid confusion.
