### ISSUE TITLE
Icon improvement suggestions

### ISSUE THREAD

**Issue by Tyriar** [waderyan/vscode-atom-keybindings#13]
Testing https://github.com/Microsoft/vscode/issues/14318

Suggestions:
- Increase size of icon as it's smaller than most extensions
- Match the keyboard's colors with the One Dark theme (blueish gray with a select few colors for the keys)

**Comment by waderyan** [comment]
Yo @bgashler1 can I get your help here? 

Could you produce a slightly larger keyboard icon? 

@Tyriar is right. The keyboard icon is noticeably smaller. 

![image](https://cloud.githubusercontent.com/assets/2449568/20015288/234d7ea4-a278-11e6-90fc-42a60fda4412.png)

**Comment by bgashler1** [comment]
[Full size.zip](https://github.com/waderyan/vscode-atom-keybindings/files/572905/Full.size.zip)

**Comment by bgashler1** [comment]
The above zip has these images full size with no padding. Let me know if you need anything else.

**Comment by waderyan** [comment]
Done (a while back, just not closed)
