### ISSUE TITLE
focusLeftEditor and focusRightEditor break OS X defaults

### ISSUE THREAD

**Issue by jefffriesen** [waderyan/vscode-atom-keybindings#2]
I realize this package is unofficial. Just a heads up these break OS X default for selecting text right or left of the current cursor position:
```
        {
            "key": "shift+cmd+left",
            "command": "workbench.action.focusLeftEditor"
        },
        {
            "key": "shift+cmd+right",
            "command": "workbench.action.focusRightEditor"
        },
```
You can see my ticket here:  https://github.com/Microsoft/vscode/issues/11991#issuecomment-246906750

**Comment by waderyan** [comment]
Fixed now. Thanks!
