### ISSUE TITLE
Multi cursor key

### ISSUE THREAD

**Issue by adambowles** [waderyan/vscode-atom-keybindings#24]
Ctrl key should insert multiple cursors on click instead of alt

Atom Keymap: 1.2.2
VS Code: 1.7.2
OS: Linux / Fedora 22

**Comment by waderyan** [comment]
Top item on our list right now. 

https://github.com/Microsoft/vscode/issues/3776

**Comment by adambowles** [comment]
Now possible: https://code.visualstudio.com/updates/v1_13#_add-multiple-cursors-with-ctrl-cmd-click
