### ISSUE TITLE
This extension forces minimap each time workspace reloads

### ISSUE THREAD

**Issue by rnemec** [waderyan/vscode-atom-keybindings#29]
No matter what settings you have
* default = false
* no setting in workspace settings.json
* enabled = false in settings.json

Each time the workspace (re)loads, the minimap.enabled setting is added if not there, and always set to true.

This is very unfriendly behavior, for people who couldn't care less about the minimap. Please, can you bring back the non-map?

**Comment by gluons** [comment]
**Stop to reproduce:**
1. Install this extension.
2. Open VSCode with project.
3. `.vscode` folder will be automatically created.
4. Remove `.vscode` folder.
5. Reopen VSCode.
6. Always same as step 3.

**Comment by alexandrudima** [comment]
We are looking into publishing a fixed version of this extension.

**Comment by alexandrudima** [comment]
We published a new version of this extension that no longer writes to workspace settings.

**Comment by rnemec** [comment]
Thank you - it works now. (Also confirming that the whole embarrassing `activate` body is now commented out)
