### ISSUE TITLE
screenshot on readme is confusing

### ISSUE THREAD

**Issue by aeschli** [waderyan/vscode-atom-keybindings#3]
Testing Microsoft/vscode#14318:

![image](https://cloud.githubusercontent.com/assets/6461412/19679196/31c7e6c4-9aa1-11e6-8fd0-26d8fa928a68.png)
- open the extension viewlet, enter 'atom key'
- look at the description on the right.
  It contains a screenshot that looks blends in so well that is is not clear that it is just an image. Silly me tried several times to click on the 'Details' , and links.

Maybe better have a real HTML table there.

**Comment by isidorn** [comment]
+1 For this, screenshot is very confussing. On top of that it looks blurry for me

**Comment by waderyan** [comment]
Thank you for the feedback.

**Comment by Tyriar** [comment]
:+1: reading this I thought that the keybindings in the screenshot may have been the only contributions (thinking as a new user).

**Comment by padamczewski** [comment]
@waderyan: I provided possible solution in #34
